import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient(window.R17_SUPABASE_URL,window.R17_SUPABASE_KEY),authView=document.querySelector('#auth-view'),appView=document.querySelector('#app-view'),feedback=document.querySelector('#auth-feedback'),vehicleFeedback=document.querySelector('#vehicle-feedback'),list=document.querySelector('#vehicles-list');
const slugify=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const currency=v=>v?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v):'Sob consulta';
async function loadVehicles(){const {data,error}=await supabase.from('vehicles').select('*').order('created_at',{ascending:false});if(error){list.innerHTML='<p class="admin-muted">Não foi possível carregar o acervo.</p>';return}list.innerHTML=data.length?data.map(v=>`<article class="vehicle-row"><div><h3>${v.brand} ${v.model}</h3><p>${v.year||'Ano sob consulta'} · ${currency(v.price)}</p></div><span>${v.status==='published'?'Publicado':v.status==='sold'?'Vendido':'Rascunho'}</span></article>`).join(''):'<p class="admin-muted">Ainda não há veículos cadastrados.</p>'}
function showApp(session){authView.hidden=!!session;appView.hidden=!session;if(session)loadVehicles()}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();feedback.textContent='Entrando…';const f=new FormData(e.currentTarget),{error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});feedback.textContent=error?'Acesso não autorizado. Verifique e-mail e senha.':''});
document.querySelector('#signout').addEventListener('click',()=>supabase.auth.signOut());
document.querySelector('#vehicle-form').addEventListener('submit',async e=>{e.preventDefault();vehicleFeedback.textContent='Salvando veículo e imagens…';const f=new FormData(e.currentTarget),brand=f.get('brand').trim(),model=f.get('model').trim(),slug=`${slugify(brand)}-${slugify(model)}-${Date.now().toString().slice(-5)}`,payload={slug,brand,model,version:f.get('version')||null,year:Number(f.get('year'))||null,mileage:Number(f.get('mileage'))||null,price:Number(f.get('price'))||null,color:f.get('color')||null,transmission:f.get('transmission')||null,fuel:f.get('fuel')||null,description:f.get('description')||null,status:f.get('status'),featured:f.get('featured')==='on'},{data:vehicle,error}=await supabase.from('vehicles').insert(payload).select().single();if(error){vehicleFeedback.textContent='Não foi possível salvar. Tente novamente.';return}const files=[...f.getAll('images')].filter(file=>file&&file.size),images=[];for(const [position,file] of files.entries()){const path=`vehicles/${vehicle.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`,{error:uploadError}=await supabase.storage.from('vehicle-media').upload(path,file,{contentType:file.type});if(!uploadError)images.push({vehicle_id:vehicle.id,path,alt:`${brand} ${model}`,position})}if(images.length)await supabase.from('vehicle_images').insert(images);e.currentTarget.reset();vehicleFeedback.textContent='Veículo salvo com sucesso.';loadVehicles()});
supabase.auth.onAuthStateChange((_e,session)=>showApp(session));supabase.auth.getSession().then(({data:{session}})=>showApp(session));
