import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const db=createClient(window.R17_SUPABASE_URL,window.R17_SUPABASE_KEY),$=s=>document.querySelector(s),form=$('#vehicle-form'),list=$('#vehicles-list'),feedback=$('#vehicle-feedback');let intent='draft',selected=[];
const money=v=>v?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v):'Sob consulta';
const slug=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function optimizeImage(file){if(!file.type.startsWith('image/')||file.type==='image/svg+xml')return file;const source=await createImageBitmap(file),limit=1920,scale=Math.min(1,limit/Math.max(source.width,source.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(source.width*scale));canvas.height=Math.max(1,Math.round(source.height*scale));canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));source.close();if(!blob)return file;const name=file.name.replace(/\.[^.]+$/,'')+'.webp';return new File([blob],name,{type:'image/webp',lastModified:Date.now()})}
function resetEditor(){form.reset();form.elements.id.value='';selected=[];queue();$('#form-label').textContent='Novo cadastro';$('#form-title').textContent='Descreva o veículo';feedback.textContent='';window.scrollTo({top:0,behavior:'smooth'})}
function parse(){const t=form.description.value,year=t.match(/\b(19\d{2}|20\d{2})\b/),km=t.match(/([\d.]+)\s*(?:mil\s*)?(?:km|kms)/i),price=t.match(/R\$\s*([\d.]+(?:,\d{1,2})?)/i),brands=['BMW','Mercedes-Benz','Porsche','Audi','Land Rover','Range Rover','Volvo','Jaguar','Lexus','Jeep','Toyota','Ford','Chevrolet','Volkswagen'];const brand=brands.find(b=>new RegExp(b,'i').test(t));if(brand)form.brand.value=brand;if(year)form.year.value=year[1];if(km)form.mileage.value=Number(km[1].replace(/\./g,''))*(/mil/i.test(km[0])?1000:1);if(price)form.price.value=Number(price[1].replace(/\./g,'').replace(',','.'));const transmission=t.match(/\b(autom[aá]tico|manual|cvt)\b/i),color=t.match(/\b(preto|branco|cinza|prata|azul|vermelho|verde|bege|marrom)\b/i);if(transmission)form.transmission.value=transmission[1];if(color)form.color.value=color[1];if(brand){const after=t.split(new RegExp(brand,'i'))[1]?.trim().split(/[,.\n]/)[0];if(after)form.model.value=after.replace(/\b(19\d{2}|20\d{2})\b.*/,'').trim()}feedback.textContent='Dados reconhecidos preenchidos. Revise antes de publicar.'}
function queue(){const box=$('#upload-queue');box.innerHTML=selected.map((f,i)=>`<div class="upload-item"><span>${esc(f.name)}</span><progress id="progress-${i}" value="0" max="100"></progress><b id="state-${i}">Aguardando</b></div>`).join('')}
async function load(){const {data,error}=await db.from('vehicles').select('*').order('created_at',{ascending:false});if(error){list.innerHTML='<p class="admin-muted">Não foi possível carregar o acervo.</p>';return}list.innerHTML=data.length?data.map(v=>`<article class="vehicle-row"><div><h3>${esc(v.brand)} ${esc(v.model)}</h3><p>${v.year||'Ano sob consulta'} · ${money(v.price)}</p></div><span>${v.status==='published'?'Publicado':v.status==='sold'?'Vendido':'Rascunho'}</span><div class="row-actions"><button class="row-action" data-edit="${v.id}">Editar</button>${v.status==='published'?`<a class="row-action" href="/veiculos/${v.slug}" target="_blank" rel="noreferrer">Ver página ↗</a>`:''}<button class="row-action delete" data-delete="${v.id}">Excluir</button></div></article>`).join(''):'<p class="admin-muted">Ainda não há veículos cadastrados.</p>'}
async function edit(id){const {data:v}=await db.from('vehicles').select('*').eq('id',id).single();if(!v)return;Object.entries(v).forEach(([k,val])=>{if(form.elements[k]&&val!==null)form.elements[k].value=val});form.featured.checked=v.featured;$('#form-label').textContent='Edição';$('#form-title').textContent=`${v.brand} ${v.model}`;window.scrollTo({top:0,behavior:'smooth'})}
async function remove(id){if(!confirm('Excluir este veículo e suas referências de imagens?'))return;const {error}=await db.from('vehicles').delete().eq('id',id);if(error)alert('Não foi possível excluir.');else load()}
list.addEventListener('click',e=>{const editId=e.target.dataset.edit,deleteId=e.target.dataset.delete;if(editId)edit(editId);if(deleteId)remove(deleteId)});$('#new-vehicle').addEventListener('click',resetEditor);$('#extract-data').addEventListener('click',parse);form.images.addEventListener('change',async e=>{selected=[...e.target.files];queue();for(const[i,file]of selected.entries()){const p=$(`#progress-${i}`),s=$(`#state-${i}`);p.value=25;s.textContent='Otimizando';try{const optimized=await optimizeImage(file);selected[i]=optimized;p.value=100;const reduction=Math.max(0,Math.round((1-optimized.size/file.size)*100));s.textContent=optimized.type==='image/webp'?`WebP · ${reduction}% menor`:'Pronta'}catch{p.value=100;s.textContent='Pronta (original)'}}});form.querySelectorAll('button[type=submit]').forEach(b=>b.addEventListener('click',()=>intent=b.dataset.status));
form.addEventListener('submit',async e=>{e.preventDefault();feedback.textContent='Salvando…';const f=new FormData(form),existing=f.get('id'),brand=f.get('brand').trim(),model=f.get('model').trim(),payload={brand,model,slug:existing?undefined:`${slug(brand)}-${slug(model)}-${Date.now().toString().slice(-5)}`,version:f.get('version')||null,year:Number(f.get('year'))||null,mileage:Number(f.get('mileage'))||null,price:Number(f.get('price'))||null,color:f.get('color')||null,transmission:f.get('transmission')||null,fuel:f.get('fuel')||null,description:f.get('description'),featured:f.get('featured')==='on',status:intent};if(!payload.slug)delete payload.slug;let vehicle,error;if(existing)({data:vehicle,error}=await db.from('vehicles').update(payload).eq('id',existing).select().single());else({data:vehicle,error}=await db.from('vehicles').insert(payload).select().single());if(error){feedback.textContent='Não foi possível salvar. Verifique os campos.';return}for(const [i,file] of selected.entries()){const p=$(`#progress-${i}`),s=$(`#state-${i}`);p.value=35;s.textContent='Enviando';const path=`vehicles/${vehicle.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`,{error:up}=await db.storage.from('vehicle-media').upload(path,file,{contentType:file.type});if(up){s.textContent='Falhou';continue}p.value=85;await db.from('vehicle_images').insert({vehicle_id:vehicle.id,path,alt:`${brand} ${model}`,position:i});p.value=100;s.textContent='Enviado'}feedback.textContent=intent==='published'?'Publicado com sucesso.':'Rascunho salvo.';selected=[];form.images.value='';load()});
function app(session){$('#auth-view').hidden=!!session;$('#app-view').hidden=!session;if(session)load()}$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),{error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});$('#auth-feedback').textContent=error?'Acesso não autorizado.':''});$('#signout').addEventListener('click',()=>db.auth.signOut());db.auth.onAuthStateChange((_e,s)=>app(s));db.auth.getSession().then(({data:{session}})=>app(session));
new MutationObserver(()=>list.querySelectorAll('a.row-action').forEach(link=>{if(link.textContent.includes('Ver página'))link.textContent='Ver veículo ↗'})).observe(list,{childList:true,subtree:true});
